version: "3"

services:
  ggosunnaefriends:
    image: rms-backend-springboot
    build: .
    ports:
      - "8080:8080"
    networks:
      - redis-network
    env_file:
      - /home/ubuntu/rms/env/springboot.env
    volumes:
      - "/home/ubuntu/rms/rms-backend-springboot:/home/ubuntu/rms/rms-backend-springboot"
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - redis-network
networks:
  redis-network:
